### ISSUE TITLE
Crashes instead of SyntaxError

### ISSUE THREAD

**Issue by Mizugola** [gura-lang/gura#4]
The following code : `t=datetime.now();k(a,b)={println(a," ","-"*b)}k(t.hour,t.min);k(t.hour+1,60-t.min);` crashes, I know it's because I forgot the ; between the }} and the k but I thought it had to raise a SyntaxError.
Sorry if creating this issue is useless :)

**Comment by ypsitau** [comment]
Thank you for your report. I've also realized this issue with v0.6.2 and corrected it for the next v0.7.0.
Sorry for my laziness of not publishing new releases frequently.

**Comment by Mizugola** [comment]
No problem :)
